import React from 'react';

const Terms = () => {
  return (
    <div style={{ padding: '2rem', lineHeight: '1.6', fontFamily: 'Arial, sans-serif' }}>
      <h1>Flipkart Terms of Use</h1>
      <p><strong>Disclaimer:</strong> In case of any discrepancy or difference, the English version will take precedence over the translation.</p>

      <p>
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable
        and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology
        Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines)
        Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name
        [www.flipkart.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)
      </p>

      <p>
        The Platform is owned by Flipkart Internet Private Limited, a company incorporated under the Companies Act, 1956 with its registered
        office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103,
        Karnataka, India and its branch offices at 2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli
        Village, Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India
        (hereinafter referred to as "Flipkart").
      </p>

      <p>
        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to
        the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform,
        You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall
        be contracting with Flipkart Internet Private Limited and these terms and conditions including the policies constitute Your binding
        obligations, with Flipkart.
      </p>

      <p>[...Document continues with membership eligibility, user account obligations, platform communication policy, buyer-seller transaction disclaimer, GST invoicing terms, charges and fee policy...]</p>
    </div>
  );
}

export default Terms;
